from __future__ import annotations

from pathlib import Path

from pygraph.scanner.walker import (
    scan_files,
)


def _write(path: Path, content: str = "") -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


class TestScanFiles:
    def test_finds_py_files(self, tmp_path: Path) -> None:
        _write(tmp_path / "main.py")
        _write(tmp_path / "utils.py")
        _write(tmp_path / "README.md")
        result = scan_files(str(tmp_path))
        paths = [f.relative_path for f in result.files]
        assert "main.py" in paths
        assert "utils.py" in paths
        assert "README.md" in paths

    def test_skips_ignored_dirs(self, tmp_path: Path) -> None:
        _write(tmp_path / "main.py")
        _write(tmp_path / "__pycache__" / "cache.py")
        _write(tmp_path / ".git" / "config")
        _write(tmp_path / ".venv" / "lib.py")
        result = scan_files(str(tmp_path))
        paths = [f.relative_path for f in result.files]
        assert "main.py" in paths
        assert "__pycache__/cache.py" not in paths
        assert ".git/config" not in paths
        assert ".venv/lib.py" not in paths

    def test_respects_gitignore(self, tmp_path: Path) -> None:
        _write(tmp_path / ".gitignore", "secret.py\n*.log\n")
        _write(tmp_path / "main.py")
        _write(tmp_path / "secret.py")
        _write(tmp_path / "debug.log")
        result = scan_files(str(tmp_path))
        paths = [f.relative_path for f in result.files]
        assert "main.py" in paths
        assert "secret.py" not in paths
        assert "debug.log" not in paths

    def test_detects_generated_files(self, tmp_path: Path) -> None:
        _write(tmp_path / "generated.py", "# Code generated by protoc. DO NOT EDIT.\n")
        _write(tmp_path / "normal.py", "def foo(): pass\n")
        result = scan_files(str(tmp_path))
        gen = {f.relative_path: f.is_generated for f in result.files}
        assert gen.get("generated.py") is True
        assert gen.get("normal.py") is False

    def test_classifies_by_extension(self, tmp_path: Path) -> None:
        _write(tmp_path / "a.py")
        _write(tmp_path / "b.html")
        _write(tmp_path / "c.json")
        _write(tmp_path / "d.yaml")
        _write(tmp_path / "e.sql")
        _write(tmp_path / "f.unknown")
        result = scan_files(str(tmp_path))
        kinds = {f.relative_path: f.kind for f in result.files}
        assert kinds["a.py"] == "py"
        assert kinds["b.html"] == "html"
        assert kinds["c.json"] == "json"
        assert kinds["d.yaml"] == "yaml"
        assert kinds["e.sql"] == "sql"
        assert kinds["f.unknown"] == "other"

    def test_scan_empty_directory(self, tmp_path: Path) -> None:
        result = scan_files(str(tmp_path))
        assert result.files == []
        assert result.errors == []

    def test_scan_non_existent_directory(self) -> None:
        result = scan_files("/nonexistent_path_xyz")
        assert result.files == []
        assert len(result.errors) > 0
