from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import pathspec

GENERATED_PATTERNS: list[str] = [
    "@generated",
    "Code generated by",
    "auto-generated",
    "This file is generated",
]

IGNORED_DIRS: set[str] = {
    ".git",
    ".pygraph",
    ".venv",
    "__pycache__",
    "node_modules",
    "venv",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "build",
    "dist",
    "*.egg-info",
    ".egg-info",
    ".tox",
    ".nox",
}

SOURCE_EXTS: dict[str, str] = {
    ".py": "py",
    ".html": "html",
    ".json": "json",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".sql": "sql",
    ".md": "md",
    ".toml": "toml",
    ".cfg": "cfg",
    ".ini": "ini",
}


@dataclass
class ScannedFile:
    path: str
    relative_path: str
    kind: str = "other"
    is_generated: bool = False


@dataclass
class ScanResult:
    files: list[ScannedFile] = field(default_factory=list)
    errors: list[Exception] = field(default_factory=list)


def _classify(path: Path) -> str:
    return SOURCE_EXTS.get(path.suffix.lower(), "other")


def _is_generated(path: Path) -> bool:
    try:
        with open(path) as f:
            first_line = f.readline(256)
        for pattern in GENERATED_PATTERNS:
            if pattern in first_line:
                return True
    except OSError:
        pass
    return False


def _load_gitignore(root: Path) -> Any:
    gitignore_path = root / ".gitignore"
    if not gitignore_path.exists():
        return None
    try:
        with open(gitignore_path) as f:
            return pathspec.PathSpec.from_lines("gitignore", f)
    except OSError:
        return None


def _should_ignore_dir(name: str) -> bool:
    if name in IGNORED_DIRS:
        return True
    return any(
        pattern.startswith("*") and name.endswith(pattern[1:])
        for pattern in IGNORED_DIRS
    )


def scan_files(root: str) -> ScanResult:
    root_path = Path(root).resolve()
    if not root_path.exists():
        return ScanResult(errors=[FileNotFoundError(f"Directory not found: {root}")])

    gitignore_spec = _load_gitignore(root_path)
    result = ScanResult()

    try:
        for entry in root_path.rglob("*"):
            if not entry.is_file():
                continue

            rel = str(entry.relative_to(root_path))

            if gitignore_spec and gitignore_spec.match_file(rel):
                continue

            parent = entry.parent
            skip = False
            for part in parent.relative_to(root_path).parts:
                if _should_ignore_dir(part):
                    skip = True
                    break
            if skip:
                continue

            kind = _classify(entry)
            is_gen = _is_generated(entry) if kind == "py" else False
            result.files.append(
                ScannedFile(
                    path=str(entry),
                    relative_path=rel,
                    kind=kind,
                    is_generated=is_gen,
                )
            )
    except OSError as e:
        result.errors.append(e)

    return result
